name: CVTimer
main: org.cubeville.cvtimer.CVTimer
author: ToeMan_
version: 1.19
api-version: 1.16
softdepend:  [PlaceholderAPI]

commands:
  cvtimer:
    aliases: timer
    permission: cvtimer.admin

permissions:

  cvtimer.admin:
    description: Gives player access to every CVTimer command
    default: op